# Generated by Django 2.2.7 on 2019-12-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
    ]
